[package]
name = "missouri"
version = "0.1.0"
edition = "2024"
description = "Show-me-state: e2e testing as directed graphs of filesystem states"

[dependencies]
camino = { version = "1", features = ["serde1"] }
clap = { version = "4", features = ["derive", "env", "unicode", "wrap_help"] }
dotenvy = "0.15"
ignore = "0.4"
indicatif = "0.17"
miette = { version = "7", features = ["fancy"] }
serde = { version = "1", features = ["derive"] }
serde_yml = "0.0"
termimad = "0.34"
tempfile = "3"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt"] }
walkdir = "2"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
